Listen 8443
<VirtualHost *:8443>
    ServerName CRM_HOST
    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/CRM_HOST/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/CRM_HOST/privkey.pem
    Header always set Strict-Transport-Security "max-age=31536000"

    ProxyPreserveHost On
    ProxyRequests Off
    RequestHeader set X-Forwarded-Proto "https"
    ProxyTimeout 720

    ProxyPass        /websocket ws://127.0.0.1:8072/websocket
    ProxyPassReverse /websocket ws://127.0.0.1:8072/websocket
    ProxyPass        / http://127.0.0.1:8069/
    ProxyPassReverse / http://127.0.0.1:8069/

    ErrorLog  ${APACHE_LOG_DIR}/crm-error.log
    CustomLog ${APACHE_LOG_DIR}/crm-access.log combined
</VirtualHost>
